// this program is automatically generated by jenerator. do not edit.
#include <jubatus/framework.hpp>
#include "convchecker_server.hpp"
#include "convchecker_serv.hpp"
using namespace jubatus;
using namespace jubatus::framework;
namespace jubatus { namespace server {
class convchecker_impl_ : public convchecker<convchecker_impl_>
{
public:
  convchecker_impl_(const server_argv& a):
    convchecker<convchecker_impl_>(a.timeout),
    p_(new convchecker_serv(a))
  {}

  bool set_config(std::string name, config_data c) //update broadcast
  { JWLOCK__(p_); return p_->set_config(c); }

  config_data get_config(std::string name) //analysis random
  { JRLOCK__(p_); return p_->get_config(); }

  std::string query(std::string name, std::string query) //update random
  { JWLOCK__(p_); return p_->query(query); }

  bool save(std::string name, std::string id) //update broadcast
  { JWLOCK__(p_); return p_->save(id); }

  bool load(std::string name, std::string id) //update broadcast
  { JWLOCK__(p_); return p_->load(id); }

  std::map<std::string,std::map<std::string,std::string > > get_status(std::string name) //analysis broadcast
  { JRLOCK__(p_); return p_->get_status(); }
  int run(){ return p_->start(*this); };
  common::cshared_ptr<convchecker_serv> get_p(){ return p_; };
private:
  common::cshared_ptr<convchecker_serv> p_;
};
}} // namespace jubatus::server
int main(int args, char** argv){
  return
    jubatus::framework::run_server<jubatus::server::convchecker_impl_,
                                   jubatus::server::convchecker_serv>
       (args, argv);
}
